import { expect, test } from '@playwright/test';
import { api, authenticatedApi } from './auth-helpers';

test('teachers fill an entire day, save timed room weeks, check materials and print without consuming stock', async ({ page }) => {
  test.setTimeout(60000);
  const errors: string[] = []; page.on('pageerror', (error) => errors.push(error.message));
  const client = await authenticatedApi(page); const suffix = Date.now();
  const roomName = 'Activity room ' + suffix, activityName = 'Tree painting ' + suffix, itemName = 'Paper ' + suffix;
  const roomResponse = await client.post(api + '/rooms', { data: { name: roomName, ageMinMonths: 24, ageMaxMonths: 60, capacity: 12 } });
  expect(roomResponse.status()).toBe(201); const room = (await roomResponse.json()).data;
  const stockResponse = await client.post(api + '/inventory', { data: { name: itemName, category: 'Art', location: 'Art cupboard', unit: 'count',
    openingQuantity: '10', reorderThreshold: '0', reason: 'Initial count', requestId: 'activity-browser-' + suffix } });
  expect(stockResponse.status()).toBe(201); const stock = (await stockResponse.json()).data;
  await page.goto('/activities');
  await page.getByRole('combobox', { name: 'Room', exact: true }).selectOption(room.id);
  await page.getByLabel('Week starting Monday', { exact: true }).fill('2026-09-14');
  await expect(page.getByRole('region', { name: 'Monday', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Add activity', exact: true }).click();
  const form = page.getByRole('form', { name: 'New activity', exact: true });
  await form.getByLabel('Activity name', { exact: true }).fill(activityName);
  await form.getByLabel('Minutes', { exact: true }).fill('25');
  await expect(form.getByLabel('Description', { exact: true })).toBeHidden();
  await form.getByText('More details', { exact: true }).click();
  await form.getByLabel('Description', { exact: true }).fill('Paint a tree and its leaves.');
  await expect(form.getByLabel('Minimum age (months)', { exact: true })).toHaveValue('24');
  await expect(form.getByLabel('Maximum age (months)', { exact: true })).toHaveValue('60');
  await form.getByRole('combobox', { name: 'Material', exact: true }).selectOption(stock.id);
  await form.getByLabel('Amount', { exact: true }).fill('6');
  await form.getByRole('button', { name: 'Add material', exact: true }).click();
  await form.getByRole('button', { name: 'Save activity', exact: true }).click();
  await expect(page.getByText('Activity saved. Choose it in the week below.', { exact: true })).toBeVisible();
  for (let index = 1; index <= 5; index++) {
    await page.getByRole('button', { name: 'Add to Monday', exact: true }).click();
    await page.getByRole('combobox', { name: 'Monday activity ' + index, exact: true }).selectOption({ label: activityName });
  }
  await page.getByLabel('Monday activity 1 start', { exact: true }).fill('07:30');
  await expect(page.getByLabel('Monday activity 1 end', { exact: true })).toHaveValue('07:55');
  await page.getByRole('button', { name: 'Tuesday', exact: true }).click();
  await page.getByRole('button', { name: 'Add to Tuesday', exact: true }).click();
  await page.getByRole('combobox', { name: 'Tuesday activity 1', exact: true }).selectOption({ label: activityName });
  const materialRow = page.getByRole('table', { name: 'Activity material availability', exact: true }).getByRole('row').filter({ hasText: itemName });
  await expect(materialRow).toContainText('36'); await expect(materialRow).toContainText('10');
  await page.getByRole('button', { name: 'Save week', exact: true }).click();
  await expect(page.getByText('Week saved.', { exact: true })).toBeVisible();
  const original = await client.get(api + '/schedule/plan?roomId=' + room.id + '&weekStart=2026-09-14');
  const saved = (await original.json()).data;
  expect(saved).toMatchObject({ version: 1, materials: [{ needed: '36', available: '10', shortage: '26' }] });
  expect(saved.entries).toHaveLength(6);
  expect(saved.entries[0]).toMatchObject({ startTime: '07:30', endTime: '07:55' });
  expect(saved.entries.filter((entry: { date: string }) => entry.date === '2026-09-14')).toHaveLength(5);
  await page.reload(); await page.getByRole('combobox', { name: 'Room', exact: true }).selectOption(room.id);
  await page.getByLabel('Week starting Monday', { exact: true }).fill('2026-09-14');
  await expect(page.getByRole('combobox', { name: 'Monday activity 1', exact: true })).toHaveValue(saved.entries[0].activityId);
  await page.getByLabel('Week starting Monday', { exact: true }).fill('2026-09-21');
  await expect(page.getByText('Nothing scheduled for this day.', { exact: true })).toBeVisible();
  await page.getByLabel('Week starting Monday', { exact: true }).fill('2026-09-14');
  await expect(page.getByRole('combobox', { name: 'Monday activity 1', exact: true })).toHaveValue(saved.entries[0].activityId);
  await page.locator('summary').filter({ hasText: /^Saved activities/ }).click();
  await page.getByRole('button', { name: 'Edit ' + activityName, exact: true }).click();
  await page.getByLabel('Activity name', { exact: true }).fill(activityName + ' updated');
  await page.getByRole('button', { name: 'Save activity', exact: true }).click();
  await expect(page.getByRole('combobox', { name: 'Monday activity 1', exact: true }).locator('option:checked')).toHaveText(activityName);
  await page.getByRole('group', { name: 'Monday activity 1', exact: true }).getByRole('button', { name: 'Use updated activity', exact: true }).click();
  await page.getByRole('button', { name: 'Save week', exact: true }).click();
  await expect(page.getByText('Week saved.', { exact: true })).toBeVisible();
  await page.emulateMedia({ media: 'print' });
  const printed = page.getByRole('table', { name: 'Weekly activity schedule for ' + roomName, exact: true });
  await expect(printed).toBeVisible(); await expect(printed).toContainText(activityName + ' updated');
  await expect(printed).toContainText('07:30–07:55');
  await expect(printed.getByText(activityName, { exact: true })).toHaveCount(5);
  await expect(page.getByRole('button', { name: 'Save week', exact: true })).toBeHidden();
  await page.emulateMedia({ media: 'screen' });
  const unchanged = await client.get(api + '/inventory/' + stock.id); expect((await unchanged.json()).data.quantity).toBe('10');
  const history = await client.get(api + '/inventory/' + stock.id + '/movements'); expect((await history.json()).total).toBe(1);
  expect(errors).toEqual([]);
});

test('Add to day starts with an empty catalog and creates and saves the activity on the selected day', async ({ page }) => {
  test.setTimeout(60000);
  const client = await authenticatedApi(page); const suffix = Date.now();
  const roomResponse = await client.post(api + '/rooms', { data: { name: 'New planner room ' + suffix, ageMinMonths: 24, ageMaxMonths: 60, capacity: 12 } });
  expect(roomResponse.status()).toBe(201); const room = (await roomResponse.json()).data;
  // Isolate the empty-catalog screen from activities made by other browser cases.
  // Creation, preview, saving and reloading still use the real API and database.
  await page.route('**/api/activity', (route) => route.fulfill({ json: { data: [] } }), { times: 1 });
  await page.goto('/activities');
  await page.getByRole('combobox', { name: 'Room', exact: true }).selectOption(room.id);
  await page.getByLabel('Week starting Monday', { exact: true }).fill('2026-09-14');
  await expect(page.getByRole('button', { name: 'Add to Monday', exact: true })).toBeEnabled();
  await page.getByRole('button', { name: 'Add to Monday', exact: true }).click();
  const form = page.getByRole('form', { name: 'New activity', exact: true });
  const name = 'Circle time ' + suffix;
  await form.getByLabel('Activity name', { exact: true }).fill(name);
  await form.getByLabel('Minutes', { exact: true }).fill('15');
  // Clicking the real submit button must report an invalid hidden field instead of doing nothing.
  await form.getByText('More details', { exact: true }).click();
  await form.getByLabel('Minimum age (months)', { exact: true }).fill('0');
  await form.getByLabel('Maximum age (months)', { exact: true }).fill('0');
  await form.getByText('More details', { exact: true }).click();
  await expect(form.getByLabel('Maximum age (months)', { exact: true })).toBeHidden();
  await form.getByRole('button', { name: 'Add to day', exact: true }).click();
  await expect(form.getByRole('alert')).toHaveText('Enter both ages in months, with maximum greater than minimum, or leave both empty for all ages.');
  await expect(form.getByLabel('Maximum age (months)', { exact: true })).toBeVisible();
  await form.getByLabel('Maximum age (months)', { exact: true }).fill('60');
  await page.getByRole('button', { name: 'Wednesday', exact: true }).click();
  await expect(form.getByRole('heading', { name: 'Add activity to Wednesday', exact: true })).toBeVisible();
  await expect(form.getByLabel('Activity name', { exact: true })).toHaveValue(name);
  await page.getByRole('button', { name: 'Continue activity for Wednesday', exact: true }).click();
  await expect(form.getByLabel('Activity name', { exact: true })).toBeFocused();
  await form.getByRole('button', { name: 'Cancel', exact: true }).click();
  await form.getByRole('button', { name: 'Keep editing', exact: true }).click();
  await expect(form.getByLabel('Activity name', { exact: true })).toHaveValue(name);
  await page.getByRole('button', { name: 'Tuesday', exact: true }).click();
  await expect(form.getByRole('heading', { name: 'Add activity to Tuesday', exact: true })).toBeVisible();
  await form.getByRole('button', { name: 'Add to day', exact: true }).click();
  await expect(page.getByRole('combobox', { name: 'Tuesday activity 1', exact: true }).locator('option:checked')).toHaveText(name);
  await expect(page.getByLabel('Tuesday activity 1 end', { exact: true })).toHaveValue('08:15');
  await page.getByRole('button', { name: 'Save week', exact: true }).click();
  await expect(page.getByText('Week saved.', { exact: true })).toBeVisible();
  const response = await client.get(api + '/schedule/plan?roomId=' + room.id + '&weekStart=2026-09-14');
  expect(response.status()).toBe(200);
  expect((await response.json()).data.entries).toEqual([expect.objectContaining({ date: '2026-09-15', startTime: '08:00', endTime: '08:15', activity: expect.objectContaining({ name }) })]);
  await page.reload(); await page.getByRole('combobox', { name: 'Room', exact: true }).selectOption(room.id);
  await page.getByLabel('Week starting Monday', { exact: true }).fill('2026-09-14');
  await page.getByRole('button', { name: 'Tuesday', exact: true }).click();
  await expect(page.getByRole('combobox', { name: 'Tuesday activity 1', exact: true }).locator('option:checked')).toHaveText(name);
  await page.getByRole('button', { name: 'Add activity', exact: true }).click();
  await form.getByLabel('Activity name', { exact: true }).fill('Cancelled activity ' + suffix);
  await form.getByRole('button', { name: 'Cancel', exact: true }).click();
  await form.getByRole('button', { name: 'Discard activity', exact: true }).click();
  await expect(form).toBeHidden();
  await expect(page.getByRole('combobox', { name: 'Tuesday activity 1', exact: true }).locator('option:checked')).toHaveText(name);
  const catalog = await client.get(api + '/activity');
  expect((await catalog.json()).data.some((activity: { name: string }) => activity.name === 'Cancelled activity ' + suffix)).toBe(false);
});
