import { authenticatedApi } from './auth-helpers';
import { expect, test } from '@playwright/test';

test('repair a missing recipe, review corrections, confirm removal and archive without losing a saved week', async ({ page }) => {
  const request = await authenticatedApi(page);
  const api = 'http://127.0.0.1:3009/api';
  const created = await request.post(`${api}/meals`, { data: { name: 'Correction breakfast', type: 'breakfast' } });
  expect(created.status()).toBe(201);
  const meal = (await created.json()).data;
  const errors: string[] = [];
  page.on('pageerror', (error) => errors.push(error.message));
  await page.goto('/meals');
  await page.getByLabel('Week starting Monday').fill('2026-10-05');
  await page.getByRole('button', { name: 'Generate Menu' }).click();
  const breakfasts = page.getByRole('combobox', { name: 'Breakfast', exact: true });
  await expect(breakfasts).toHaveCount(5);
  for (let day = 0; day < 5; day++) await breakfasts.nth(day).selectOption(meal.id);
  await page.getByLabel('Children', { exact: true }).fill('4');
  await page.getByLabel('Staff', { exact: true }).fill('1');
  const save = page.getByRole('button', { name: 'Save Menu' });
  const print = page.getByRole('button', { name: 'Print List' });
  await expect(page.getByText('Complete the recipes before saving or printing this shopping list.')).toBeVisible();
  await expect(save).toBeDisabled(); await expect(print).toBeDisabled();
  await page.getByRole('button', { name: 'Edit recipe for Correction breakfast' }).first().click();
  await expect(page.getByRole('heading', { name: 'Recipe for Correction breakfast' })).toBeVisible();
  await page.getByLabel('Ingredient name', { exact: true }).fill('Correction eggs');
  await page.getByRole('button', { name: 'Add ingredient', exact: true }).click();
  await expect(page.getByText('Ingredient added.', { exact: true })).toBeVisible();
  await page.getByLabel('Recipe ingredient', { exact: true }).selectOption({ label: 'Correction eggs (count)' });
  await page.getByLabel('Quantity per person', { exact: true }).fill('1');
  await page.getByRole('button', { name: 'Add to recipe' }).click();
  await expect(page.getByText('Ingredient added to the recipe.')).toBeVisible();
  await expect(page.getByLabel('Recipe ingredient', { exact: true }).getByRole('option', { name: 'Correction eggs (count)' })).toHaveCount(0);
  await page.getByRole('button', { name: 'Planner', exact: true }).click();
  await expect(save).toBeEnabled();
  await page.getByLabel('Correction eggs in house (count)', { exact: true }).fill('2');
  await expect(save).toBeEnabled();
  const row = page.getByRole('table').getByRole('row').filter({ hasText: 'Correction eggs' });
  await expect(row.getByText('23 count', { exact: true })).toBeVisible();
  await save.click();
  await expect(page.getByText('Menu, headcounts and stock saved together.')).toBeVisible();
  await page.getByRole('button', { name: 'Meal Setup', exact: true }).click();
  await page.getByLabel('Choose meal', { exact: true }).selectOption(meal.id);
  const quantity = page.getByLabel('Correction eggs quantity per person (count)', { exact: true });
  await expect(quantity).toBeEnabled(); await quantity.fill('2');
  await page.getByRole('button', { name: 'Save quantity for Correction eggs' }).click();
  await expect(page.getByText('Recipe quantity updated.')).toBeVisible();
  // A saved week keeps history until the user explicitly adopts current recipes.
  await page.getByRole('button', { name: 'Planner', exact: true }).click();
  await expect(row.getByText('23 count', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Use current recipes' }).click();
  await expect(row.getByText('48 count', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Meal Setup', exact: true }).click();
  await page.getByLabel('Choose meal', { exact: true }).selectOption(meal.id);
  const remove = page.getByRole('button', { name: 'Remove Correction eggs from recipe' });
  page.once('dialog', (dialog) => { void dialog.dismiss(); });
  await remove.click(); await expect(quantity).toBeVisible();
  page.once('dialog', (dialog) => { void dialog.accept(); });
  await remove.click();
  await expect(page.getByText('Ingredient removed from this recipe.')).toBeVisible();
  await page.getByRole('button', { name: 'Planner', exact: true }).click();
  await expect(page.getByText('Complete the recipes before saving or printing this shopping list.')).toBeVisible();
  await expect(save).toBeDisabled(); await expect(print).toBeDisabled();
  await page.getByRole('button', { name: 'Meal Setup', exact: true }).click();
  await page.getByLabel('Choose meal', { exact: true }).selectOption(meal.id);
  page.once('dialog', (dialog) => { void dialog.accept(); });
  await page.getByRole('button', { name: 'Archive meal' }).click();
  await expect(page.getByText('Meal archived.')).toBeVisible();
  await page.getByRole('button', { name: 'Planner', exact: true }).click();
  page.once('dialog', (dialog) => { void dialog.accept(); });
  await page.getByRole('button', { name: 'Reopen saved week' }).click();
  await expect(row.getByText('23 count', { exact: true })).toBeVisible();
  await expect(print).toBeEnabled();
  const shopping = (await (await request.get(`${api}/menu/plans/2026-10-05/shopping`)).json()).data;
  expect(shopping.items.find((item: { ingredient: { name: string } }) => item.ingredient.name === 'Correction eggs'))
    .toMatchObject({ quantity: 25, inStorage: 2, toBuy: 23 });
  expect(errors).toEqual([]);
});
