import { expect, test } from '@playwright/test';
import { api, authenticatedApi } from './auth-helpers';

test('check in by room, reload, correct a visit with history and check out through real HTTP', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', (error) => errors.push(error.message));
  const http = await authenticatedApi(page);
  const createdRoom = await http.post(api + '/rooms', { data: { name: 'Browser attendance room', ageMinMonths: 18, ageMaxMonths: 72, capacity: 20 } });
  expect(createdRoom.status()).toBe(201);
  const room = (await createdRoom.json()).data;
  const createdChild = await http.post(api + '/children', { data: { firstName: 'Browser', lastName: 'Attendance Child', dateOfBirth: '2022-03-01', roomId: room.id } });
  expect(createdChild.status()).toBe(201);
  const child = await createdChild.json();
  const config = await (await http.get(api + '/attendance/config')).json();
  await page.goto('/attendance');
  await page.getByRole('combobox', { name: 'Attendance room', exact: true }).selectOption(room.id);
  const row = page.getByRole('row', { name: 'Browser Attendance Child', exact: true });
  await expect(row.getByText('Not checked in', { exact: true })).toBeVisible();
  await row.getByRole('button', { name: 'Check in Browser Attendance Child', exact: true }).click();
  await expect(row.getByText('Present', { exact: true })).toBeVisible();
  await page.reload();
  await expect(row.getByText('Present', { exact: true })).toBeVisible();
  const records = await (await http.get(api + '/attendance?childId=' + child.id)).json();
  expect(records).toHaveLength(1);
  const visit = records[0];
  const repeated = await http.post(api + '/attendance/checkin', { data: { childId: child.id, roomId: room.id, date: config.today } });
  expect((await repeated.json()).id).toBe(visit.id);
  await row.getByRole('button', { name: 'Correct / history', exact: true }).click();
  const form = page.getByRole('region', { name: 'Attendance record', exact: true });
  await expect(form.getByText('No corrections recorded.')).toBeVisible();
  await form.getByRole('checkbox', { name: 'Void mistaken or duplicate visit', exact: true }).check();
  await form.getByLabel('Correction reason', { exact: true }).fill('Synthetic visit entered for the wrong arrival.');
  page.once('dialog', (dialog) => { void dialog.accept(); });
  await form.getByRole('button', { name: 'Save correction', exact: true }).click();
  await expect(page.getByText('Attendance correction saved with its history.')).toBeVisible();
  await row.getByRole('button', { name: 'Correct / history', exact: true }).click();
  await expect(form.getByText('Synthetic visit entered for the wrong arrival.')).toBeVisible();
  const history = await (await http.get(api + '/attendance/' + visit.id + '/corrections')).json();
  expect(history).toHaveLength(1);
  expect(history[0]).toMatchObject({ before: { checkIn: visit.checkIn, voided: false }, after: { checkIn: visit.checkIn, voided: true }, actorUsername: 'browser-admin' });
  await form.getByRole('button', { name: 'Close record', exact: true }).click();
  await row.getByRole('button', { name: 'Check in Browser Attendance Child', exact: true }).click();
  await expect(row.getByText('Present', { exact: true })).toBeVisible();
  await row.getByRole('button', { name: 'Check out Browser Attendance Child', exact: true }).click();
  await expect(row.getByText('Checked out', { exact: true })).toBeVisible();
  await page.reload();
  await expect(row.getByText('Checked out', { exact: true })).toBeVisible();
  const after = await (await http.get(api + '/attendance?childId=' + child.id)).json();
  expect(after).toHaveLength(2);
  expect(after.filter((record: { checkOut: string | null; voided: boolean }) => !record.voided && !record.checkOut)).toHaveLength(0);
  expect(errors).toEqual([]);
});
