import { expect, test } from '@playwright/test';
import { api, authenticatedApi } from './auth-helpers';

test('simple daily amounts, count checks and history persist through HTTP and reloads', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', (error) => errors.push(error.message));
  const client = await authenticatedApi(page);
  const name = 'Synthetic inventory ' + Date.now(), groupName = 'Classroom supplies ' + Date.now();
  await page.goto('/inventory');
  await page.locator('header summary').filter({ hasText: /^More$/ }).click();
  await page.getByRole('button', { name: 'Add group', exact: true }).click();
  await page.getByLabel('Group name', { exact: true }).fill(groupName);
  await page.getByRole('combobox', { name: 'Group type', exact: true }).selectOption('supplies');
  await page.getByRole('button', { name: 'Save group', exact: true }).click();
  await expect(page.getByText('Group created. Add the items you keep here.', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Add item', exact: true }).click();
  await page.getByLabel('1. What is it?', { exact: true }).fill(name);
  const groupChoice = page.getByRole('form', { name: 'Add item', exact: true }).getByRole('combobox', { name: 'Group', exact: true, includeHidden: true });
  await expect(groupChoice).toHaveCount(1);
  await expect(groupChoice).toBeHidden();
  await page.getByLabel('3. Where do you keep it?', { exact: true }).fill('Art room / Cupboard / Shelf 2');
  await page.getByRole('combobox', { name: 'Measured in', exact: true }).selectOption('pack');
  await page.getByLabel('2. How much do you have?', { exact: true }).fill('10');
  await page.getByText('Optional details', { exact: true }).click();
  await page.getByLabel('Show a warning when this much is left', { exact: true }).fill('2');
  await page.getByRole('button', { name: 'Save item', exact: true }).click();
  await expect(page.getByText('Item added.', { exact: true })).toBeVisible();
  const row = page.getByRole('row').filter({ has: page.getByText(name, { exact: true }) });
  const more = async () => { const details = row.locator('details'); if (!(await details.evaluate((node) => (node as HTMLDetailsElement).open))) await details.locator('summary').click(); };
  const search = async () => {
    await page.getByRole('searchbox', { name: 'Search items' }).fill(name);
    await page.getByRole('button', { name: 'Search', exact: true }).click(); await expect(row).toBeVisible();
  };
  await search(); await expect(row.getByText('10 packs', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Bought more ' + name, exact: true }).click();
  await expect(page.getByRole('button', { name: 'Save amount', exact: true })).toBeEnabled();
  await expect(page.getByLabel('Received date', { exact: true })).toBeHidden();
  await page.getByLabel('How much did you buy? (packs)', { exact: true }).fill('0.5');
  await page.getByRole('button', { name: 'Save amount', exact: true }).click();
  await expect(page.getByText('Added to what you have.', { exact: true })).toBeVisible();
  await expect(row.getByText('10.5 packs', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Used some ' + name, exact: true }).click();
  await page.getByLabel('How much did you use? (packs)', { exact: true }).fill('9');
  await expect(page.getByText('1.5 packs left.', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Save amount', exact: true }).click();
  await expect(page.getByText('Amount updated.', { exact: true })).toBeVisible();
  await expect(row.getByText('Low stock', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Used some ' + name, exact: true }).click();
  await page.getByLabel('How much did you use? (packs)', { exact: true }).fill('2');
  await page.getByRole('button', { name: 'Save amount', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Usage cannot exceed the stock currently available.');
  await page.getByRole('button', { name: 'Cancel', exact: true }).click();
  await more(); await page.getByRole('button', { name: 'Check amount for ' + name, exact: true }).click();
  await page.getByLabel('How much is there now? (packs)', { exact: true }).fill('0');
  await page.getByRole('button', { name: 'Save amount', exact: true }).click();
  await expect(page.getByText('Amount updated.', { exact: true })).toBeVisible();
  await expect(row.getByText('Out of stock', { exact: true })).toBeVisible();
  await more(); await page.getByRole('button', { name: 'Edit ' + name, exact: true }).click();
  await page.getByLabel('Where is it stored?', { exact: true }).fill('Art room / Cupboard / Shelf 3');
  await page.getByText('Add a note (optional)', { exact: true }).click();
  await page.getByLabel('Notes (optional)', { exact: true }).fill('Relabeled storage bin');
  await page.getByRole('button', { name: 'Save details', exact: true }).click();
  await expect(page.getByText('Details saved.', { exact: true })).toBeVisible();
  await page.reload();
  await page.getByRole('button', { name: 'Open group ' + groupName, exact: true }).click(); await search();
  await page.getByText('More filters', { exact: true }).click();
  await page.getByRole('combobox', { name: 'Stock status', exact: true }).selectOption('out');
  await expect(row.getByText('Art room / Cupboard / Shelf 3', { exact: true })).toBeVisible();
  await more(); await page.getByRole('button', { name: 'History for ' + name, exact: true }).click();
  const history = page.getByRole('region', { name: 'Inventory history', exact: true });
  for (const reason of ['Initial quantity recorded', 'Purchase received', 'Used in daily activities', 'Physical count checked', 'Relabeled storage bin']) await expect(history.getByText(reason, { exact: true })).toBeVisible();
  await expect(history.getByText('5 recorded changes. Corrections add a record and retain earlier counts.', { exact: true })).toBeVisible();
  const response = await client.get(api + '/inventory?q=' + encodeURIComponent(name)); expect(response.status()).toBe(200);
  const saved = (await response.json()).items[0];
  expect(saved).toMatchObject({ quantity: '0', unit: 'pack', version: 5, location: 'Art room / Cupboard / Shelf 3', status: 'out' });
  const persisted = await client.get(api + '/inventory/' + saved.id + '/movements');
  expect((await persisted.json()).items.map((movement: { delta: string }) => movement.delta)).toEqual(['0', '-1.5', '-9', '0.5', '10']);
  expect(errors).toEqual([]);
});

test('typing an existing food name uses its recipe identifier without a separate linking step', async ({ page }) => {
  const client = await authenticatedApi(page); const suffix = Date.now();
  const foodName = 'Food stock ' + suffix, ingredientName = 'Synthetic oats ' + suffix;
  const ingredientResponse = await client.post(api + '/ingredients', { data: { name: ingredientName, unit: 'lb' } });
  expect(ingredientResponse.status()).toBe(201); const ingredient = (await ingredientResponse.json()).data;
  await page.goto('/inventory');
  await page.locator('header summary').filter({ hasText: /^More$/ }).click();
  await page.getByRole('button', { name: 'Add group', exact: true }).click();
  await page.getByLabel('Group name', { exact: true }).fill(foodName);
  await page.getByRole('combobox', { name: 'Group type', exact: true }).selectOption('food');
  await page.getByRole('button', { name: 'Save group', exact: true }).click();
  await expect(page.getByText('Group created. Add the items you keep here.', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Add item', exact: true }).click();
  await page.getByLabel('1. What is it?', { exact: true }).fill(ingredientName);
  await expect(page.getByRole('combobox', { name: 'Measured in', exact: true })).toHaveValue('lb');
  await page.getByLabel('2. How much do you have?', { exact: true }).fill('2');
  await page.getByRole('button', { name: 'Kitchen pantry', exact: true }).click();
  const sent = page.waitForRequest((request) => request.method() === 'POST' && request.url().endsWith('/api/inventory'));
  await page.getByRole('button', { name: 'Save item', exact: true }).click();
  expect((await sent).postDataJSON()).toMatchObject({ ingredientId: ingredient.id, openingQuantity: '2' });
  await expect(page.getByText('Item added.', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'All groups', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Open group ' + foodName, exact: true })).toContainText('1 item');
});
