import { expect, test } from '@playwright/test';
import { api, authenticatedApi } from './auth-helpers';

test('inventory counts, location edits and movement history persist through real HTTP and page reloads', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', (error) => errors.push(error.message));
  const client = await authenticatedApi(page);
  const name = 'Synthetic inventory ' + Date.now();
  await page.goto('/inventory');
  await page.getByRole('button', { name: 'Add inventory item', exact: true }).click();
  await page.getByRole('textbox', { name: 'Item name', exact: true }).fill(name);
  await page.getByLabel('Category', { exact: true }).fill('Synthetic supplies');
  await page.getByLabel('Exact storage location', { exact: true }).fill('Art room / Cupboard / Shelf 2');
  await page.getByRole('combobox', { name: 'Unit', exact: true }).selectOption('pack');
  await page.getByRole('textbox', { name: 'Opening count', exact: true }).fill('10');
  await page.getByRole('textbox', { name: 'Reorder threshold', exact: true }).fill('2');
  await page.getByRole('textbox', { name: 'Reason', exact: true }).fill('Initial physical count');
  await page.getByRole('button', { name: 'Save inventory item', exact: true }).click();
  await expect(page.getByText('Inventory item created with its opening count.', { exact: true })).toBeVisible();
  const search = async () => {
    await page.getByRole('searchbox', { name: 'Search items', exact: true }).fill(name);
    await page.getByRole('button', { name: 'Search', exact: true }).click();
    await expect(page.getByRole('button', { name: 'History for ' + name, exact: true })).toBeVisible();
  };
  await search();
  const row = page.getByRole('row').filter({ has: page.getByRole('button', { name: 'History for ' + name, exact: true }) });
  await expect(row.getByRole('cell', { name: '10 pack', exact: true })).toBeVisible();
  const adjust = async (type: string, quantity: string, reason: string) => {
    await page.getByRole('button', { name: 'Adjust ' + name, exact: true }).click();
    await page.getByRole('combobox', { name: 'Change type', exact: true }).selectOption(type);
    await page.getByRole('textbox', { name: type === 'correction' ? 'Count observed (pack)' : 'Quantity (pack)', exact: true }).fill(quantity);
    await page.getByRole('textbox', { name: 'Reason', exact: true }).fill(reason);
    await page.getByRole('button', { name: 'Record stock change', exact: true }).click();
    await expect(page.getByText('Stock change recorded.', { exact: true })).toBeVisible();
    await expect(page.getByRole('button', { name: 'Adjust ' + name, exact: true })).toBeEnabled();
  };
  await adjust('addition', '0.5', 'Small stock addition');
  await expect(row.getByRole('cell', { name: '10.5 pack', exact: true })).toBeVisible();
  await adjust('usage', '9', 'Class supplies');
  await expect(row.getByRole('cell', { name: '1.5 pack', exact: true })).toBeVisible();
  await expect(row.getByText('Low stock', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Adjust ' + name, exact: true }).click();
  await page.getByRole('combobox', { name: 'Change type', exact: true }).selectOption('usage');
  await page.getByRole('textbox', { name: 'Quantity (pack)', exact: true }).fill('2');
  await page.getByRole('textbox', { name: 'Reason', exact: true }).fill('Attempt to use too much');
  await page.getByRole('button', { name: 'Record stock change', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Usage cannot exceed the stock currently available.');
  await page.getByRole('button', { name: 'Cancel', exact: true }).click();
  await adjust('correction', '0', 'Physical recount: empty bin');
  await expect(row.getByText('Out of stock', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Edit ' + name, exact: true }).click();
  await page.getByLabel('Exact storage location', { exact: true }).fill('Art room / Cupboard / Shelf 3');
  await page.getByRole('textbox', { name: 'Reason', exact: true }).fill('Relabeled storage bin');
  await page.getByRole('button', { name: 'Save inventory item', exact: true }).click();
  await expect(page.getByText('Inventory details updated and recorded in history.', { exact: true })).toBeVisible();
  await page.reload();
  await search();
  await page.getByRole('combobox', { name: 'Stock status', exact: true }).selectOption('out');
  await expect(row.getByText('Art room / Cupboard / Shelf 3', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'History for ' + name, exact: true }).click();
  const history = page.getByRole('region', { name: 'Inventory history', exact: true });
  for (const reason of ['Initial physical count', 'Small stock addition', 'Class supplies', 'Physical recount: empty bin', 'Relabeled storage bin']) {
    await expect(history.getByText(reason, { exact: true })).toBeVisible();
  }
  await expect(history.getByText('5 recorded changes. Corrections add a record and retain earlier counts.', { exact: true })).toBeVisible();
  const response = await client.get(api + '/inventory?q=' + encodeURIComponent(name));
  expect(response.status()).toBe(200);
  const saved = (await response.json()).items[0];
  expect(saved).toMatchObject({ quantity: '0', unit: 'pack', version: 5, location: 'Art room / Cupboard / Shelf 3', status: 'out' });
  const persisted = await client.get(api + '/inventory/' + saved.id + '/movements');
  expect((await persisted.json()).items.map((movement: { delta: string }) => movement.delta)).toEqual(['0', '-1.5', '-9', '0.5', '10']);
  expect(errors).toEqual([]);
});
