import { expect, test } from '@playwright/test';
import { api, authenticatedApi } from './auth-helpers';

test('staff changes persist, update active totals and leave sign-in accounts unchanged', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', (error) => errors.push(error.message));
  const apiClient = await authenticatedApi(page);
  const suffix = Date.now().toString();
  const name = 'Synthetic Staff ' + suffix;
  const updatedName = 'Updated Staff ' + suffix;
  const roomName = 'Staff Room ' + suffix;
  const accountsBefore = await apiClient.get(api + '/admin/accounts');
  expect(accountsBefore.status()).toBe(200);
  const accounts = await accountsBefore.json();
  const initial = await apiClient.get(api + '/staff');
  expect(initial.status()).toBe(200);
  const activeTotal = (await initial.json()).activeTotal;
  const roomResponse = await apiClient.post(api + '/rooms', { data: { name: roomName, ageMinMonths: 24, ageMaxMonths: 60, capacity: 12 } });
  expect(roomResponse.status()).toBe(201);
  const room = (await roomResponse.json()).data;

  await page.goto('/staff');
  await page.getByRole('button', { name: 'Add staff', exact: true }).click();
  await page.getByRole('textbox', { name: 'Full name', exact: true }).fill(name);
  await page.getByRole('textbox', { name: 'Job role', exact: true }).fill('Teacher');
  await page.getByRole('combobox', { name: 'Assigned room (optional)', exact: true }).selectOption(room.id);
  await page.getByRole('button', { name: 'Save staff', exact: true }).click();
  await expect(page.getByText('Staff record created.', { exact: true })).toBeVisible();
  await page.getByRole('searchbox', { name: 'Search staff', exact: true }).fill(name);
  await page.getByRole('button', { name: 'Search', exact: true }).click();
  await expect(page.getByRole('rowheader', { name, exact: true })).toBeVisible();
  const createdResponse = await apiClient.get(api + '/staff?q=' + encodeURIComponent(name));
  const saved = (await createdResponse.json()).items[0];
  expect(saved).toMatchObject({ name, role: 'Teacher', roomId: room.id, active: true });
  await page.getByRole('button', { name: 'Edit ' + name, exact: true }).click();
  await page.getByRole('textbox', { name: 'Full name', exact: true }).fill(updatedName);
  await page.getByRole('textbox', { name: 'Job role', exact: true }).fill('Lead teacher');
  await page.getByRole('button', { name: 'Save staff', exact: true }).click();
  await expect(page.getByText(/Staff record updated/)).toBeVisible();
  await page.getByRole('searchbox', { name: 'Search staff', exact: true }).fill(updatedName);
  await page.getByRole('button', { name: 'Search', exact: true }).click();
  await expect(page.getByRole('rowheader', { name: updatedName, exact: true })).toBeVisible();
  await page.getByRole('combobox', { name: 'Filter by room', exact: true }).selectOption(room.id);
  await expect(page.getByRole('rowheader', { name: updatedName, exact: true })).toBeVisible();
  page.once('dialog', (dialog) => { void dialog.accept(); });
  await page.getByRole('button', { name: 'Deactivate ' + updatedName, exact: true }).click();
  await expect(page.getByText(updatedName + ' deactivated. Select Inactive or All statuses to view the preserved record.', { exact: true })).toBeVisible();
  await page.getByRole('combobox', { name: 'Status', exact: true }).selectOption('false');
  const row = page.getByRole('row').filter({ has: page.getByRole('rowheader', { name: updatedName, exact: true }) });
  await expect(row).toContainText('Inactive');
  await expect(row).toContainText(roomName);
  await page.reload();
  await page.getByRole('combobox', { name: 'Status', exact: true }).selectOption('false');
  await page.getByRole('searchbox', { name: 'Search staff', exact: true }).fill(updatedName);
  await page.getByRole('button', { name: 'Search', exact: true }).click();
  await expect(row).toContainText('Lead teacher');
  const retained = await apiClient.get(api + '/staff/' + saved.id);
  expect((await retained.json()).data).toMatchObject({ id: saved.id, name: updatedName, active: false, roomId: room.id, version: 3 });
  expect((await (await apiClient.get(api + '/admin/accounts')).json())).toEqual(accounts);
  expect((await (await apiClient.get(api + '/dashboard')).json()).totalStaff).toBe(activeTotal);
  await page.getByRole('button', { name: 'Edit ' + updatedName, exact: true }).click();
  await page.getByRole('checkbox', { name: 'Active staff member' }).check();
  await page.getByRole('button', { name: 'Save staff', exact: true }).click();
  await expect(page.getByText(/Staff record updated/)).toBeVisible();
  await page.getByRole('link', { name: 'Home', exact: true }).click();
  await expect(page.getByText('Active Staff', { exact: true }).locator('..')).toContainText(String(activeTotal + 1));
  expect(errors).toEqual([]);
});
