import { authenticatedApi } from './auth-helpers';
import { expect, test } from '@playwright/test';

test('save, reload, preserve drafts and reopen two independent weeks through real HTTP', async ({ page }) => {
  const request = await authenticatedApi(page);
  const api = 'http://127.0.0.1:3009/api';
  const mealResponse = await request.post(`${api}/meals`, { data: { name: 'Egg breakfast', type: 'breakfast' } });
  expect(mealResponse.status()).toBe(201);
  const meal = (await mealResponse.json()).data;
  const ingredientResponse = await request.post(`${api}/ingredients`, { data: { name: 'Eggs', unit: 'count' } });
  expect(ingredientResponse.status()).toBe(201);
  const eggs = (await ingredientResponse.json()).data;
  expect((await request.post(`${api}/inventory`, { data: { name: 'Weekly eggs', category: 'Food', location: 'Kitchen / Shelf 1',
    ingredientId: eggs.id, unit: 'count', openingQuantity: '2', reorderThreshold: '0', reason: 'Opening count', requestId: crypto.randomUUID() } })).status()).toBe(201);
  expect((await request.post(`${api}/meals/${meal.id}/ingredients`, { data: { ingredientId: eggs.id, quantity: 1 } })).status()).toBe(201);
  const catalog = (await (await request.get(`${api}/meals`)).json()).data as { id: string; name: string }[];
  const oatmeal = catalog.find((item) => item.name === 'Oatmeal')!;
  const errors: string[] = [];
  page.on('pageerror', (error) => errors.push(error.message));
  page.on('dialog', (dialog) => { void dialog.accept(); });
  await page.goto('/meals');
  await page.getByLabel('Week starting Monday').fill('2026-09-07');
  const generate = page.getByRole('button', { name: 'Generate Menu' });
  const save = page.getByRole('button', { name: 'Save Menu' });
  await expect(generate).toBeEnabled();
  await generate.click();
  const breakfasts = page.getByRole('combobox', { name: 'Breakfast', exact: true });
  await expect(breakfasts).toHaveCount(5);
  for (let i = 0; i < 5; i++) await breakfasts.nth(i).selectOption(i < 3 ? meal.id : oatmeal.id);
  await page.getByLabel('Children', { exact: true }).fill('4');
  await page.getByLabel('Staff', { exact: true }).fill('1');
  await expect(save).toBeEnabled();
  await expect(save).toBeEnabled();
  const eggRow = page.getByRole('table').getByRole('row').filter({ hasText: 'Eggs' });
  await expect(eggRow.getByText('15 count', { exact: true })).toBeVisible();
  await expect(eggRow.getByText('13 count', { exact: true })).toBeVisible();
  await save.click();
  await expect(page.getByText('Menu and shopping list saved.')).toBeVisible();
  await page.reload();
  await expect(page.getByRole('button', { name: 'Print List' })).toBeEnabled();
  await expect(save).toBeDisabled();
  await expect(page.getByLabel('Children', { exact: true })).toHaveValue('4');
  await expect(page.getByLabel('Eggs recorded stock', { exact: true })).toHaveText('2 count');
  await expect(eggRow.getByText('13 count', { exact: true })).toBeVisible();
  await page.getByLabel('Children', { exact: true }).fill('6');
  await page.getByRole('button', { name: 'Meal Setup', exact: true }).click();
  await page.getByRole('button', { name: 'Planner', exact: true }).click();
  await expect(page.getByLabel('Children', { exact: true })).toHaveValue('6');
  await page.getByLabel('Week starting Monday').fill('2026-09-14');
  await expect(generate).toBeEnabled();
  await generate.click();
  await expect(save).toBeEnabled();
  await save.click();
  await expect(page.getByText('Menu and shopping list saved.')).toBeVisible();
  await page.getByLabel('Week starting Monday').fill('2026-09-07');
  await expect(page.getByLabel('Children', { exact: true })).toHaveValue('6');
  await page.getByRole('button', { name: 'Reopen saved week' }).click();
  await expect(page.getByLabel('Children', { exact: true })).toHaveValue('4');
  await expect(page.getByRole('button', { name: 'Print List' })).toBeEnabled();
  const savedShopping = (await (await request.get(`${api}/shelf/final?weekStart=2026-09-07`)).json()).data;
  expect(savedShopping.items.find((item: { ingredient: { id: string } }) => item.ingredient.id === eggs.id)).toMatchObject({ quantity: 15, inStorage: 2, toBuy: 13 });
  await page.setViewportSize({ width: 390, height: 844 });
  const navigation = page.getByRole('navigation', { name: 'Mobile navigation' });
  await expect(navigation).toBeVisible();
  await navigation.getByRole('button', { name: 'More', exact: true }).click();
  const more = page.getByRole('dialog', { name: 'More', exact: true });
  await expect(more).toBeVisible();
  await more.getByRole('button', { name: 'Close more' }).click();
  await expect(more).toHaveCount(0);
  await navigation.getByRole('link', { name: 'Meals', exact: true }).click();
  // Opening navigation or reselecting the current page must not reset its saved week.
  await expect(page.getByLabel('Children', { exact: true })).toHaveValue('4');
  await expect(page.getByRole('button', { name: 'Print List' })).toBeEnabled();
  expect(errors).toEqual([]);
});
